[package]
name = "dherg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.7"
chrono = "0.4.42"
octocrab = "0.48.0"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
